-- Seed data for public_prompts (PromptShip)
-- Upsert version: safe to re-run

INSERT INTO public_prompts
  (uuid, slug, title, description, model, content_json, thumbnail_url, tags, views, copies, is_featured, is_public)
VALUES
  (
    'pp_001',
    'neon-detective-rain',
    'Neon Detective in the Rain',
    'A moody cyberpunk opening with neon reflections and rain-soaked streets.',
    'Sora',
    '{"title":"Neon Detective in the Rain","logline":"A lone detective walks through neon rain.","style_lock":"cyberpunk noir, neon reflections, rain-soaked asphalt, 35mm grain","characters":[{"id":"detective","anchors":"trench coat, fedora, glowing cigarette ember, wet hair","prompt":"Character reference sheet, detective in trench coat and fedora, glowing cigarette ember, wet hair, neutral pose, front view, side view, back view, neon rain lighting"}],"scene_prompt":"Neon-lit alley in heavy rain, reflective asphalt, steam vents, cyberpunk signage, moody noir.","shots":[{"id":1,"duration":4,"description":"Wide shot of the detective walking through neon rain as signs flicker.","transition":"cut","camera_movement":"slow tracking","composition":"wide, centered","lighting":"neon reflections","audio_sfx":"rain and distant traffic","prompt_en":"detective in trench coat, neon rain, flickering signs, reflective asphalt, wide shot, noir"},{"id":2,"duration":3,"description":"Close-up of the detective lighting a cigarette, rain drops in bokeh.","transition":"cut","camera_movement":"static close-up","composition":"tight face","lighting":"neon rim light","audio_sfx":"lighter click","prompt_en":"close-up detective lighting cigarette, neon rim light, rain bokeh, noir"},{"id":3,"duration":4,"description":"Low angle shot of boots splashing through puddles.","transition":"cut","camera_movement":"low tracking","composition":"tight on boots","lighting":"wet reflections","audio_sfx":"splashing steps","prompt_en":"low angle boots splashing puddles, neon reflections, rain"},{"id":4,"duration":4,"description":"Match cut to the detective stopping under a glowing sign, smoke rising.","transition":"match cut","camera_movement":"slow push in","composition":"medium, sign framing","lighting":"glowing sign","audio_sfx":"rain fade","prompt_en":"detective under glowing sign, smoke rising, neon noir, medium shot"}],"master_prompt":"Cinematic neon rain, slow tracking, noir mood, neon reflections, professional shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Neon rain and wet trench coat remain consistent."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["cyberpunk","noir","rain"]',
    1250,
    342,
    true,
    true
  ),
  (
    'pp_002',
    'luxury-perfume-splash',
    'Luxury Perfume Water Splash',
    'A premium product shot with slow motion water splash and glass reflections.',
    'Veo',
    '{"title":"Luxury Perfume Water Splash","logline":"A luxury perfume bottle emerges from a slow water splash.","style_lock":"studio black, glossy reflections, slow motion elegance","characters":[],"scene_prompt":"Premium perfume bottle on black acrylic, water splash frozen mid-air, studio black background.","shots":[{"id":1,"duration":3,"description":"Macro shot of the bottle label with droplets sliding down.","transition":"cut","camera_movement":"macro push in","composition":"tight label","lighting":"soft rim light","audio_sfx":"water drip","prompt_en":"macro perfume label, droplets sliding, glossy reflections, studio black"},{"id":2,"duration":3,"description":"Slow motion splash arcs behind the bottle.","transition":"cut","camera_movement":"slow pan","composition":"centered product","lighting":"high specular","audio_sfx":"splash","prompt_en":"slow motion water splash, perfume bottle centered, glossy reflections"},{"id":3,"duration":3,"description":"Close-up of the glass cap catching light.","transition":"cut","camera_movement":"macro tilt","composition":"tight cap","lighting":"sparkle highlights","audio_sfx":"soft chime","prompt_en":"glass cap macro, sparkle highlights, premium studio"},{"id":4,"duration":3,"description":"Wide hero shot with light sweep across the bottle.","transition":"cut","camera_movement":"slow dolly in","composition":"hero product","lighting":"light sweep","audio_sfx":"ambient shimmer","prompt_en":"wide hero shot, light sweep across perfume bottle, studio black"}],"master_prompt":"Macro product shot, slow motion water splash, studio lighting, glossy reflections, premium ad sequence.","negative_prompt":"low quality, noisy, watermark","continuity_notes":"Studio black background and glossy reflections remain consistent."}',
    'https://fal.media/files/panda/5pQ-2R9wS_1s7sE_z.png',
    '["advertising","product","slow-motion"]',
    4500,
    1200,
    true,
    true
  ),
  (
    'pp_003',
    'fpv-forest-chase',
    'FPV Drone Forest Chase',
    'A fast FPV drone sequence weaving through a dense forest canopy.',
    'Kling',
    '{"title":"FPV Drone Forest Chase","logline":"A high-speed FPV chase through forest trails.","style_lock":"high-speed FPV, dynamic motion blur, sunbeams through trees","characters":[{"id":"runner","anchors":"orange jacket, trail backpack, running headlamp","prompt":"Character reference sheet, runner in orange jacket, trail backpack, headlamp, neutral pose, front view, side view, back view, forest light"}],"scene_prompt":"Dense forest trail, sunbeams through tall trees, dusty air, fast-paced FPV energy.","shots":[{"id":1,"duration":3,"description":"FPV dives between trees following the runner on the trail.","transition":"cut","camera_movement":"fpv dive","composition":"wide chase","lighting":"sunbeams","audio_sfx":"wind rush","prompt_en":"fpv chase through forest, runner in orange jacket, sunbeams, motion blur"},{"id":2,"duration":3,"description":"Quick bank around a tree as the runner cuts a corner.","transition":"cut","camera_movement":"fpv bank","composition":"dynamic diagonal","lighting":"dappled light","audio_sfx":"branch whoosh","prompt_en":"fpv bank around tree, runner cutting corner, dynamic motion"},{"id":3,"duration":3,"description":"Low pass over the trail, leaves scattering.","transition":"cut","camera_movement":"low fpv pass","composition":"low angle","lighting":"forest glow","audio_sfx":"leaves rustle","prompt_en":"low fpv pass over trail, leaves scattering, sunbeams"},{"id":4,"duration":3,"description":"Pull up to reveal the runner exiting into a clearing.","transition":"cut","camera_movement":"fpv pull up","composition":"wide reveal","lighting":"bright clearing","audio_sfx":"wind fade","prompt_en":"fpv pull up reveal, runner exits into clearing, bright sunlight"}],"master_prompt":"FPV drone chase, fast banking turns, sunbeams through trees, dynamic motion blur, professional shot list.","negative_prompt":"low quality, jitter, watermark","continuity_notes":"Runner orange jacket and forest trail remain consistent."}',
    'https://fal.media/files/tiger/7jM-1X5wN_6s9sA_r.png',
    '["fpv","action","nature"]',
    2100,
    560,
    false,
    true
  ),
  (
    'pp_004',
    'midnight-subway-heist',
    'Midnight Subway Heist',
    'A tense underground chase with precise shot-by-shot pacing.',
    'Sora',
    '{"title":"Midnight Subway Heist","logline":"A courier flees through an empty subway after a midnight handoff goes wrong.","style_lock":"35mm film, high contrast, cool teal shadows, low-key lighting, subtle grain","characters":[{"id":"courier","anchors":"black hoodie, scar on left eyebrow, messenger bag with red strap","prompt":"Character reference sheet, young courier, black hoodie, scar on left eyebrow, red strap messenger bag, neutral pose, front view, side view, back view, cinematic lighting"},{"id":"pursuer","anchors":"long trench coat, short hair, earpiece","prompt":"Character reference sheet, pursuer in long trench coat, short hair, earpiece, neutral pose, front view, side view, back view, cinematic lighting"}],"scene_prompt":"Empty subway platform at night, flickering fluorescent lights, cool teal shadows, light haze, reflective tiles, cinematic 35mm look.","shots":[{"id":1,"duration":4,"description":"Wide establishing shot of an empty subway platform, fluorescent lights flicker as the courier enters frame.","camera_movement":"slow dolly in","composition":"wide, centered subject","lighting":"cool fluorescent, pools of shadow","audio_sfx":"distant train rumble","prompt_en":"empty subway platform at night, lone courier in black hoodie with red strap messenger bag, wide shot, flickering fluorescent lights, cool teal shadows, cinematic 35mm"},{"id":2,"duration":3,"description":"Close-up of the courier glancing back, breath visible in cold air.","camera_movement":"static close-up","composition":"tight on face","lighting":"rim light from overhead tubes","audio_sfx":"sharp inhale","prompt_en":"close-up face, scar on left eyebrow, cold breath, rim light, tense expression, cinematic"},{"id":3,"duration":4,"description":"Low tracking shot as the courier sprints along the platform, bag bouncing.","camera_movement":"low tracking","composition":"leading lines, shallow depth","lighting":"streaked highlights","audio_sfx":"footsteps echo","prompt_en":"low angle tracking shot, courier running, messenger bag with red strap, motion blur, fluorescent streaks, cinematic"},{"id":4,"duration":4,"description":"Medium shot as the pursuer appears at the far end, trench coat swinging.","camera_movement":"slow push in","composition":"subject framed by tunnel","lighting":"backlit haze","audio_sfx":"distant radio chatter","prompt_en":"medium shot, pursuer in long trench coat, backlit tunnel haze, cinematic noir"},{"id":5,"duration":5,"description":"Whip pan to the courier jumping into a departing train, doors closing.","camera_movement":"whip pan","composition":"dynamic, motion blur","lighting":"sparks and reflections","audio_sfx":"train doors slam","prompt_en":"whip pan, courier jumps into moving train, door closing, motion blur, sparks, reflections, cinematic action"}],"master_prompt":"Cinematic subway chase, 35mm film, cool teal shadows, low-key lighting, subtle grain, empty platform, courier with black hoodie and red strap messenger bag, pursuer in trench coat, suspense pacing, professional shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Courier keeps red strap bag, pursuer appears after shot 2, empty platform throughout."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["thriller","cinematic","chase","urban","night"]',
    980,
    210,
    true,
    true
  ),
  (
    'pp_005',
    'desert-wind-turbine-doc',
    'Desert Wind Turbine Doc',
    'A documentary-style sequence about clean energy in the desert.',
    'Veo',
    '{"title":"Desert Wind Turbine Doc","logline":"A sunrise documentary of wind turbines powering a desert town.","style_lock":"documentary realism, natural light, warm sunrise palette, crisp detail","characters":[{"id":"technician","anchors":"workwear jacket, safety vest, sun hat, clipboard","prompt":"Character reference sheet, renewable energy technician, workwear jacket, safety vest, sun hat, holding clipboard, neutral pose, front view, side view, back view, documentary lighting"}],"scene_prompt":"Desert plain at sunrise, wind turbines in the distance, dusty air, warm golden light, documentary realism.","shots":[{"id":1,"duration":4,"description":"Aerial wide shot over a desert plain as turbines spin at sunrise.","camera_movement":"slow aerial glide","composition":"wide landscape","lighting":"golden hour","audio_sfx":"soft wind","prompt_en":"aerial wide shot, desert plain, wind turbines spinning, golden sunrise, documentary realism"},{"id":2,"duration":4,"description":"Medium shot of turbine blades sweeping past the camera.","camera_movement":"static, blades pass","composition":"off-center blade sweep","lighting":"warm edge light","audio_sfx":"whoosh of blades","prompt_en":"medium shot, turbine blades sweeping, warm edge light, documentary style"},{"id":3,"duration":4,"description":"Cut to a local worker checking a control panel in a small facility.","camera_movement":"handheld slight","composition":"medium close-up","lighting":"soft interior window light","audio_sfx":"panel beeps","prompt_en":"worker checking control panel, warm interior light, documentary handheld"},{"id":4,"duration":4,"description":"Wide shot of a small desert town with turbines on the horizon.","camera_movement":"slow push in","composition":"town foreground, turbines background","lighting":"morning sun","audio_sfx":"quiet ambience","prompt_en":"desert town wide shot, turbines on horizon, morning sun, documentary"}],"master_prompt":"Documentary sequence about wind energy, desert sunrise, natural light, warm palette, realistic details, professional shot list.","negative_prompt":"low quality, oversaturated, watermark","continuity_notes":"Same sunrise time, consistent warm palette."}',
    'https://fal.media/files/panda/5pQ-2R9wS_1s7sE_z.png',
    '["documentary","nature","aerial","energy","sunrise"]',
    740,
    190,
    false,
    true
  ),
  (
    'pp_006',
    'startup-pitch-night',
    'Startup Pitch Night',
    'A high-pressure demo night with crisp corporate visuals.',
    'Sora',
    '{"title":"Startup Pitch Night","logline":"A founder delivers a critical pitch as the clock runs down.","style_lock":"clean corporate, modern glass, cool white key light, subtle bloom","characters":[{"id":"founder","anchors":"navy blazer, white sneakers, silver laptop","prompt":"Character reference sheet, startup founder, navy blazer, white sneakers, holding silver laptop, neutral pose, front view, side view, back view, clean corporate lighting"}],"scene_prompt":"Modern demo night stage, large presentation screen with charts, cool white key light, blue accent lights, glass surfaces.","shots":[{"id":1,"duration":3,"description":"Wide shot of a stage with a large screen showing charts.","camera_movement":"slow dolly in","composition":"wide, centered stage","lighting":"cool white key, blue accents","audio_sfx":"low crowd murmur","prompt_en":"wide stage, startup demo night, large screen charts, cool white lighting, corporate cinematic"},{"id":2,"duration":4,"description":"Medium shot of the founder gesturing with a clicker.","camera_movement":"steady cam","composition":"rule of thirds","lighting":"spotlight with soft fill","audio_sfx":"clicker sound","prompt_en":"founder in navy blazer, white sneakers, holding clicker, soft spotlight, corporate cinematic"},{"id":3,"duration":4,"description":"Close-up of the silver laptop with a live dashboard.","camera_movement":"macro push in","composition":"tight on screen","lighting":"screen glow","audio_sfx":"soft keyboard taps","prompt_en":"close-up silver laptop, live dashboard UI, screen glow, macro cinematic"},{"id":4,"duration":4,"description":"Cut to judges watching intently, subtle nods.","camera_movement":"static medium","composition":"line of judges","lighting":"soft top light","audio_sfx":"room tone","prompt_en":"judges watching, focused expressions, soft top light, corporate documentary"},{"id":5,"duration":4,"description":"Wide shot as a countdown timer hits zero and applause starts.","camera_movement":"slow zoom out","composition":"wide with timer","lighting":"stage lights flare","audio_sfx":"applause swell","prompt_en":"stage wide shot, countdown timer hits zero, applause, stage lights flare, cinematic"}],"master_prompt":"Corporate demo night, modern glass stage, cool white key light, crisp detail, confident founder, professional shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Same stage, same founder outfit, screen charts throughout."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["corporate","startup","presentation","night","cinematic"]',
    610,
    170,
    false,
    true
  ),
  (
    'pp_007',
    'mythic-forest-ritual',
    'Mythic Forest Ritual',
    'A fantasy ritual sequence with glowing artifacts and fog.',
    'Kling',
    '{"title":"Mythic Forest Ritual","logline":"A group of mystics awakens an ancient artifact in a moonlit forest.","style_lock":"fantasy cinematic, blue moonlight, mist, glowing runes, soft bloom","characters":[{"id":"mystic","anchors":"hooded robe, glowing rune necklace, silver staff","prompt":"Character reference sheet, mystic in hooded robe, glowing rune necklace, silver staff, neutral pose, front view, side view, back view, moonlit lighting"}],"scene_prompt":"Moonlit forest clearing, thick mist, ancient stone altar, glowing runes, soft bloom, blue palette.","shots":[{"id":1,"duration":4,"description":"Wide shot of a moonlit forest clearing with thick mist.","camera_movement":"slow crane down","composition":"wide, symmetrical trees","lighting":"blue moonlight","audio_sfx":"whispering wind","prompt_en":"moonlit forest clearing, thick mist, blue moonlight, fantasy cinematic"},{"id":2,"duration":4,"description":"Medium shot of a glowing artifact on a stone altar.","camera_movement":"slow push in","composition":"centered artifact","lighting":"glow from runes","audio_sfx":"low hum","prompt_en":"glowing artifact on stone altar, runes, soft bloom, fantasy"},{"id":3,"duration":4,"description":"Close-up of a mystic placing a hand on the artifact, light intensifies.","camera_movement":"static close-up","composition":"hands and light","lighting":"glow spill","audio_sfx":"pulse sound","prompt_en":"close-up hands touching glowing artifact, light intensifies, mist, cinematic fantasy"},{"id":4,"duration":5,"description":"Wide shot as light rises into the trees, fog swirling.","camera_movement":"slow pull back","composition":"wide with light beam","lighting":"blue moon + artifact glow","audio_sfx":"crescendo","prompt_en":"wide shot, light beam rising into trees, swirling fog, fantasy cinematic"}],"master_prompt":"Fantasy ritual in a moonlit forest, glowing runes, mist, blue palette, soft bloom, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Moonlight and mist remain constant."}',
    'https://fal.media/files/tiger/7jM-1X5wN_6s9sA_r.png',
    '["fantasy","cinematic","ritual","moonlight","atmospheric"]',
    530,
    140,
    false,
    true
  ),
  (
    'pp_008',
    'street-food-night-market',
    'Street Food Night Market',
    'A vibrant travel piece focused on motion, steam, and flavors.',
    'Veo',
    '{"title":"Street Food Night Market","logline":"A night market chef prepares a signature dish in a busy alley.","style_lock":"handheld travel, neon accents, warm steam, vibrant colors","characters":[{"id":"chef","anchors":"short apron, rolled sleeves, steel spatula, confident smile","prompt":"Character reference sheet, street food chef, short apron, rolled sleeves, steel spatula, confident smile, neutral pose, front view, side view, back view, neon stall light"}],"scene_prompt":"Crowded night market alley, neon signs, warm steam, sizzling stalls, handheld travel energy.","shots":[{"id":1,"duration":3,"description":"Wide shot of a crowded night market alley with neon signs.","camera_movement":"handheld walk-in","composition":"wide, busy crowd","lighting":"neon + warm stalls","audio_sfx":"market chatter","prompt_en":"night market alley, neon signs, crowded stalls, handheld travel style"},{"id":2,"duration":3,"description":"Medium shot of the chef slicing ingredients quickly.","camera_movement":"handheld close","composition":"medium, fast hands","lighting":"warm stall light","audio_sfx":"knife chops","prompt_en":"chef slicing ingredients, fast hands, warm stall light, handheld"},{"id":3,"duration":3,"description":"Close-up of sizzling pan with steam and flames.","camera_movement":"macro tilt","composition":"tight on pan","lighting":"orange flame glow","audio_sfx":"sizzle","prompt_en":"close-up sizzling pan, steam, flames, macro shot, vibrant"},{"id":4,"duration":4,"description":"Customer receives the dish, smiles, takes a bite.","camera_movement":"steady medium","composition":"two-shot","lighting":"neon rim light","audio_sfx":"ambient crowd","prompt_en":"customer smiling, takes a bite, neon rim light, travel cinematic"},{"id":5,"duration":4,"description":"Final wide shot of the alley, steam rising as the camera pulls back.","camera_movement":"slow pull back","composition":"wide farewell","lighting":"neon haze","audio_sfx":"fade out ambience","prompt_en":"wide night market alley, steam rising, neon haze, slow pull back"}],"master_prompt":"Travel night market sequence, handheld energy, neon accents, warm steam, vibrant colors, professional shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Same alley, neon palette, steam visible in each shot."}',
    'https://fal.media/files/panda/5pQ-2R9wS_1s7sE_z.png',
    '["travel","food","night","handheld","urban"]',
    870,
    230,
    true,
    true
  ),
  (
    'pp_009',
    'rooftop-chase-dawn',
    'Rooftop Chase at Dawn',
    'A sunrise rooftop chase with fast cuts and long shadows.',
    'Sora',
    '{"title":"Rooftop Chase at Dawn","logline":"A runner escapes across rooftops as the city wakes up.","style_lock":"warm sunrise, long shadows, kinetic camera, crisp detail","characters":[{"id":"runner","anchors":"red windbreaker, black joggers, white sneakers","prompt":"Character reference sheet, athletic runner, red windbreaker, black joggers, white sneakers, neutral pose, front view, side view, back view, sunrise light"},{"id":"pursuer","anchors":"dark hoodie, fingerless gloves, determined expression","prompt":"Character reference sheet, pursuer in dark hoodie, fingerless gloves, determined expression, neutral pose, front view, side view, back view, sunrise light"}],"scene_prompt":"Urban rooftops at dawn, warm sunrise glow, long shadows, skyline in distance.","shots":[{"id":1,"duration":3,"description":"Wide aerial shot of rooftops as the runner bursts into frame.","transition":"cut","camera_movement":"aerial glide","composition":"wide skyline","lighting":"golden sunrise","audio_sfx":"wind rush","prompt_en":"rooftops at dawn, runner in red windbreaker, warm sunrise, aerial wide shot"},{"id":2,"duration":3,"description":"Low tracking shot along the rooftop edge as the runner sprints.","transition":"cut","camera_movement":"low tracking","composition":"leading lines","lighting":"long shadows","audio_sfx":"footsteps","prompt_en":"low tracking shot, runner sprinting, long shadows, sunrise glow"},{"id":3,"duration":3,"description":"Quick whip pan to the pursuer vaulting a gap.","transition":"whip pan","camera_movement":"whip pan","composition":"dynamic motion blur","lighting":"warm rim light","audio_sfx":"gravel skid","prompt_en":"pursuer vaulting gap, whip pan, motion blur, sunrise rim light"},{"id":4,"duration":4,"description":"Wide shot as both characters leap between buildings.","transition":"match cut","camera_movement":"slow tilt up","composition":"wide with skyline","lighting":"sun flares","audio_sfx":"breath and wind","prompt_en":"wide shot, two figures leaping between rooftops, skyline sunrise, cinematic"}],"master_prompt":"Rooftop chase at dawn, warm sunrise, long shadows, kinetic camera, athletic runner, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Runner red windbreaker remains visible, sunrise lighting consistent."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["cinematic","thriller","drone","montage"]',
    520,
    140,
    false,
    true
  ),
  (
    'pp_010',
    'museum-glass-heist',
    'Museum Glass Heist',
    'A stealth heist inside a silent museum hall.',
    'Kling',
    '{"title":"Museum Glass Heist","logline":"A thief slips past laser security to steal a glass artifact.","style_lock":"cool museum lighting, glossy reflections, quiet tension","characters":[{"id":"thief","anchors":"dark suit, slim gloves, earpiece","prompt":"Character reference sheet, sleek thief in dark suit, slim gloves, earpiece, neutral pose, front view, side view, back view, cool gallery light"}],"scene_prompt":"Modern museum hall, glass cases, cool white lights, polished floors, laser security beams.","shots":[{"id":1,"duration":4,"description":"Wide shot of the silent museum hall with glass cases.","transition":"cut","camera_movement":"slow dolly in","composition":"wide symmetrical","lighting":"cool white","audio_sfx":"soft hum","prompt_en":"silent museum hall, glass cases, cool white light, symmetrical wide shot"},{"id":2,"duration":3,"description":"Close-up of the thief cutting a laser beam with a mirror.","transition":"cut","camera_movement":"static close-up","composition":"tight hands","lighting":"specular reflections","audio_sfx":"quiet breath","prompt_en":"close-up gloved hands, mirror deflecting laser beam, glossy reflections"},{"id":3,"duration":4,"description":"Medium shot of the thief opening the glass case.","transition":"cut","camera_movement":"slow push in","composition":"rule of thirds","lighting":"cool highlights","audio_sfx":"glass latch","prompt_en":"thief opening glass case, cool highlights, tense atmosphere"},{"id":4,"duration":4,"description":"Match cut to the artifact lifted with both hands.","transition":"match cut","camera_movement":"static medium","composition":"centered artifact","lighting":"soft glow","audio_sfx":"subtle alarm beep","prompt_en":"artifact lifted, soft glow, centered frame, cinematic tension"}],"master_prompt":"Museum heist, cool lighting, glossy reflections, stealth tension, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Museum stays silent, laser beams remain active until final shot."}',
    'https://fal.media/files/tiger/7jM-1X5wN_6s9sA_r.png',
    '["thriller","cinematic","advertising"]',
    410,
    110,
    false,
    true
  ),
  (
    'pp_011',
    'ocean-rescue-helicopter',
    'Ocean Rescue Helicopter',
    'A documentary rescue with strong wind and sea spray.',
    'Veo',
    '{"title":"Ocean Rescue Helicopter","logline":"A rescue team descends into stormy seas to save a sailor.","style_lock":"documentary realism, cold wind, sea spray, muted palette","characters":[{"id":"rescuer","anchors":"bright orange suit, helmet visor, safety harness","prompt":"Character reference sheet, rescuer in bright orange suit, helmet visor, safety harness, neutral pose, front view, side view, back view, stormy light"}],"scene_prompt":"Stormy ocean, rescue helicopter hovering, sea spray, gray clouds, documentary realism.","shots":[{"id":1,"duration":4,"description":"Wide shot of the helicopter hovering above rough waves.","transition":"cut","camera_movement":"aerial hover","composition":"wide ocean","lighting":"overcast","audio_sfx":"helicopter blades","prompt_en":"helicopter hovering, rough ocean waves, gray clouds, documentary style"},{"id":2,"duration":4,"description":"Medium shot of the rescuer clipped to a cable descending.","transition":"cut","camera_movement":"steady cam","composition":"centered subject","lighting":"cold rim light","audio_sfx":"wind roar","prompt_en":"rescuer in orange suit descending on cable, cold wind, sea spray"},{"id":3,"duration":4,"description":"Close-up of a soaked sailor reaching up from the raft.","transition":"cut","camera_movement":"handheld close-up","composition":"tight face","lighting":"soft diffused light","audio_sfx":"waves crashing","prompt_en":"close-up soaked sailor, reaching up, waves, documentary realism"},{"id":4,"duration":4,"description":"Wide shot as the rescuer pulls the sailor up.","transition":"cut","camera_movement":"slow pull back","composition":"wide rescue","lighting":"overcast","audio_sfx":"radio chatter","prompt_en":"rescuer pulling sailor up, helicopter cable, stormy sea"}],"master_prompt":"Ocean rescue documentary, helicopter, stormy waves, muted palette, cinematic realism.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Stormy sea and orange rescue suit remain consistent."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["documentary","cinematic","slow-motion"]',
    380,
    95,
    false,
    true
  ),
  (
    'pp_012',
    'retro-diner-breakup',
    'Retro Diner Breakup',
    'A quiet breakup scene in a neon diner booth.',
    'Sora',
    '{"title":"Retro Diner Breakup","logline":"Two lovers part ways over coffee in a retro diner.","style_lock":"neon glow, warm tungsten, shallow depth, subtle film grain","characters":[{"id":"woman","anchors":"red dress, short bob haircut, silver necklace","prompt":"Character reference sheet, woman in red dress, short bob haircut, silver necklace, neutral pose, front view, side view, back view, neon diner light"},{"id":"man","anchors":"brown leather jacket, stubble, white t-shirt","prompt":"Character reference sheet, man in brown leather jacket, stubble, white t-shirt, neutral pose, front view, side view, back view, neon diner light"}],"scene_prompt":"Retro diner booth, neon window sign, coffee cups, warm tungsten lighting, rainy street outside.","shots":[{"id":1,"duration":4,"description":"Wide shot of the neon diner booth with both characters seated.","transition":"cut","camera_movement":"slow push in","composition":"two-shot","lighting":"warm neon mix","audio_sfx":"soft jazz","prompt_en":"retro diner booth, neon glow, two characters seated, warm tungsten light"},{"id":2,"duration":4,"description":"Close-up of the woman staring into her coffee.","transition":"cut","camera_movement":"static close-up","composition":"tight face","lighting":"soft neon rim","audio_sfx":"cup clink","prompt_en":"close-up woman in red dress, reflective mood, neon rim light"},{"id":3,"duration":4,"description":"Close-up of the man swallowing hard, eyes down.","transition":"cut","camera_movement":"static close-up","composition":"tight face","lighting":"warm key light","audio_sfx":"quiet breath","prompt_en":"close-up man in leather jacket, stubble, warm key light, tense emotion"},{"id":4,"duration":4,"description":"Match cut to the neon sign flickering outside.","transition":"match cut","camera_movement":"slow tilt up","composition":"sign detail","lighting":"neon flicker","audio_sfx":"neon buzz","prompt_en":"neon diner sign flicker, rainy street, cinematic"}],"master_prompt":"Retro diner breakup scene, neon glow, warm tungsten, emotional close-ups, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Neon lighting and rainy street remain consistent."}',
    'https://fal.media/files/panda/5pQ-2R9wS_1s7sE_z.png',
    '["cinematic","handheld","thriller"]',
    360,
    90,
    false,
    true
  ),
  (
    'pp_013',
    'sci-fi-medbay-wakeup',
    'Sci-Fi Medbay Wakeup',
    'A patient awakens in a sterile futuristic medbay.',
    'Kling',
    '{"title":"Sci-Fi Medbay Wakeup","logline":"A patient wakes to glowing monitors and sterile light.","style_lock":"cool blue light, sterile glass, soft bloom, sci-fi realism","characters":[{"id":"patient","anchors":"white medical gown, short hair, wrist band","prompt":"Character reference sheet, patient in white medical gown, short hair, wrist band, neutral pose, front view, side view, back view, cool blue light"}],"scene_prompt":"Futuristic medbay, glowing holographic monitors, sterile glass walls, cool blue lighting.","shots":[{"id":1,"duration":4,"description":"Wide shot of the medbay pods with blue ambient light.","transition":"cut","camera_movement":"slow dolly in","composition":"wide, symmetrical","lighting":"cool blue","audio_sfx":"low hum","prompt_en":"futuristic medbay pods, blue ambient light, sterile glass, cinematic"},{"id":2,"duration":4,"description":"Close-up of the patient opening their eyes.","transition":"cut","camera_movement":"static close-up","composition":"tight face","lighting":"soft blue glow","audio_sfx":"monitor beep","prompt_en":"close-up patient eyes opening, cool blue glow, sci-fi atmosphere"},{"id":3,"duration":4,"description":"Medium shot of monitors reflecting in glass as the patient sits up.","transition":"cut","camera_movement":"slow push in","composition":"medium, glass reflections","lighting":"cool highlights","audio_sfx":"fabric rustle","prompt_en":"patient sits up, glass reflections, holographic monitors, sci-fi medbay"},{"id":4,"duration":4,"description":"Wide shot as the door slides open, light spills in.","transition":"cut","camera_movement":"slow pull back","composition":"wide with door","lighting":"bright spill light","audio_sfx":"door hiss","prompt_en":"medbay door slides open, bright light spill, cinematic sci-fi"}],"master_prompt":"Sci-fi medbay wakeup, cool blue lighting, sterile glass, soft bloom, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Cool blue light and sterile glass remain consistent."}',
    'https://fal.media/files/tiger/7jM-1X5wN_6s9sA_r.png',
    '["sci-fi","cinematic","montage"]',
    340,
    85,
    false,
    true
  ),
  (
    'pp_014',
    'snow-mountain-survival',
    'Snow Mountain Survival',
    'A survival sequence in a whiteout mountain storm.',
    'Veo',
    '{"title":"Snow Mountain Survival","logline":"A climber pushes through a whiteout to reach shelter.","style_lock":"cold desaturated palette, heavy snow, handheld grit","characters":[{"id":"climber","anchors":"blue parka, frost-covered goggles, ice axe","prompt":"Character reference sheet, climber in blue parka, frost goggles, ice axe, neutral pose, front view, side view, back view, snowy light"}],"scene_prompt":"Snowy mountain ridge, whiteout storm, blowing snow, low visibility, harsh wind.","shots":[{"id":1,"duration":4,"description":"Wide shot of the climber battling a whiteout on the ridge.","transition":"cut","camera_movement":"handheld wide","composition":"wide, subject small","lighting":"flat overcast","audio_sfx":"howling wind","prompt_en":"climber on snowy ridge, whiteout storm, blowing snow, handheld documentary"},{"id":2,"duration":4,"description":"Close-up of frost on goggles, breath visible.","transition":"cut","camera_movement":"static close-up","composition":"tight face","lighting":"soft diffused","audio_sfx":"heavy breathing","prompt_en":"close-up frost on goggles, breath visible, cold desaturated palette"},{"id":3,"duration":4,"description":"Medium shot as the climber plants the ice axe and climbs.","transition":"cut","camera_movement":"handheld medium","composition":"diagonal lines","lighting":"flat light","audio_sfx":"ice crunch","prompt_en":"climber planting ice axe, snow crunch, handheld gritty"},{"id":4,"duration":4,"description":"Wide shot of a faint shelter light in the distance.","transition":"match cut","camera_movement":"slow push in","composition":"wide, distant light","lighting":"dim glow","audio_sfx":"wind fade","prompt_en":"distant shelter light, whiteout storm, cinematic survival"}],"master_prompt":"Snow mountain survival, whiteout storm, cold desaturated palette, handheld grit, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Heavy snow and low visibility persist across shots."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["documentary","cinematic","handheld"]',
    320,
    80,
    false,
    true
  ),
  (
    'pp_015',
    'luxury-watch-macro',
    'Luxury Watch Macro',
    'A macro advertising sequence highlighting a premium watch.',
    'Sora',
    '{"title":"Luxury Watch Macro","logline":"Macro shots reveal every detail of a premium watch.","style_lock":"studio black, soft rim light, high gloss reflections","characters":[],"scene_prompt":"Premium watch on black velvet, soft rim light, studio reflections.","shots":[{"id":1,"duration":3,"description":"Macro shot of the watch face with sweeping second hand.","transition":"cut","camera_movement":"macro push in","composition":"tight dial","lighting":"soft rim light","audio_sfx":"tick","prompt_en":"macro watch face, sweeping second hand, glossy reflections, studio black"},{"id":2,"duration":3,"description":"Close-up of the crown and engraved logo.","transition":"cut","camera_movement":"macro tilt","composition":"tight detail","lighting":"specular highlights","audio_sfx":"metal click","prompt_en":"macro crown detail, engraved logo, specular highlights, premium"},{"id":3,"duration":3,"description":"Slow motion droplets slide over the bezel.","transition":"dissolve","camera_movement":"slow macro slide","composition":"tight texture","lighting":"controlled reflections","audio_sfx":"water drip","prompt_en":"slow motion droplets on watch bezel, macro, studio reflections"},{"id":4,"duration":3,"description":"Wide product shot with light sweep across the case.","transition":"cut","camera_movement":"slow dolly in","composition":"centered product","lighting":"light sweep","audio_sfx":"soft chime","prompt_en":"wide product shot, light sweep across watch case, studio black"}],"master_prompt":"Luxury watch macro ad, studio black, soft rim light, glossy reflections, premium detail shots.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Studio black background and rim light remain consistent."}',
    'https://fal.media/files/panda/5pQ-2R9wS_1s7sE_z.png',
    '["advertising","cinematic","slow-motion"]',
    290,
    75,
    true,
    true
  ),
  (
    'pp_016',
    'savannah-lion-tracking',
    'Savannah Lion Tracking',
    'A wildlife documentary following a lion at dusk.',
    'Veo',
    '{"title":"Savannah Lion Tracking","logline":"A lion moves through tall grass as the sun sets.","style_lock":"documentary realism, warm dusk, natural lens flares","characters":[{"id":"lion","anchors":"scarred right ear, golden mane, amber eyes","prompt":"Character reference sheet, lion with scarred right ear, golden mane, amber eyes, neutral pose, front view, side view, back view, dusk light"}],"scene_prompt":"Savannah at dusk, tall golden grass, warm sun, distant acacia trees.","shots":[{"id":1,"duration":4,"description":"Wide shot of the lion moving through tall grass.","transition":"cut","camera_movement":"slow tracking","composition":"wide, low angle","lighting":"warm dusk","audio_sfx":"rustling grass","prompt_en":"lion in tall grass, warm dusk light, documentary wide shot"},{"id":2,"duration":4,"description":"Close-up of the lion eyes scanning the horizon.","transition":"cut","camera_movement":"static close-up","composition":"tight eyes","lighting":"golden rim","audio_sfx":"soft breath","prompt_en":"close-up lion eyes, amber glow, warm rim light"},{"id":3,"duration":4,"description":"Medium shot as the lion pauses near an acacia tree.","transition":"cut","camera_movement":"slow push in","composition":"medium, tree silhouette","lighting":"sun flare","audio_sfx":"distant birds","prompt_en":"lion near acacia tree, sun flare, documentary realism"},{"id":4,"duration":4,"description":"Wide silhouette as the sun dips below the horizon.","transition":"match cut","camera_movement":"slow pull back","composition":"silhouette wide","lighting":"sunset silhouette","audio_sfx":"evening ambience","prompt_en":"lion silhouette at sunset, wide shot, warm sky"}],"master_prompt":"Savannah lion documentary, warm dusk light, tall grass, natural lens flares, cinematic realism.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Golden mane and scarred ear remain visible when possible."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["documentary","cinematic","travel"]',
    260,
    70,
    false,
    true
  ),
  (
    'pp_017',
    'dance-practice-studio',
    'Dance Practice Studio',
    'A kinetic montage of a dance crew rehearsing.',
    'Kling',
    '{"title":"Dance Practice Studio","logline":"A crew rehearses in a mirrored studio with sharp lighting.","style_lock":"clean studio, crisp highlights, energetic pacing","characters":[{"id":"lead-dancer","anchors":"white hoodie, black shorts, high-top sneakers","prompt":"Character reference sheet, lead dancer in white hoodie, black shorts, high-top sneakers, neutral pose, front view, side view, back view, studio light"}],"scene_prompt":"Mirrored dance studio, bright overhead lights, polished floor, minimal props.","shots":[{"id":1,"duration":3,"description":"Wide shot of the crew forming lines in the mirror.","transition":"cut","camera_movement":"steady wide","composition":"wide symmetry","lighting":"bright studio light","audio_sfx":"music beat","prompt_en":"dance crew in mirrored studio, wide shot, bright lights"},{"id":2,"duration":3,"description":"Medium shot of the lead dancer hitting a sharp move.","transition":"cut","camera_movement":"handheld slight","composition":"centered subject","lighting":"clean highlights","audio_sfx":"beat drop","prompt_en":"lead dancer sharp move, studio lighting, energetic"},{"id":3,"duration":3,"description":"Close-up of sneakers sliding on the floor.","transition":"cut","camera_movement":"low close-up","composition":"tight on feet","lighting":"glossy reflections","audio_sfx":"shoe squeak","prompt_en":"close-up sneakers sliding, polished floor, studio reflections"},{"id":4,"duration":3,"description":"Wide shot with the crew hitting a synchronized pose.","transition":"cut","camera_movement":"slow push in","composition":"wide, group symmetry","lighting":"bright top light","audio_sfx":"music pause","prompt_en":"crew synchronized pose, mirrored studio, bright top light"}],"master_prompt":"Dance practice montage, mirrored studio, crisp highlights, energetic pacing, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Same studio and wardrobe throughout."}',
    'https://fal.media/files/tiger/7jM-1X5wN_6s9sA_r.png',
    '["cinematic","montage","handheld"]',
    240,
    60,
    false,
    true
  ),
  (
    'pp_018',
    'haunted-hallway',
    'Haunted Hallway',
    'A horror sequence in a dim, flickering corridor.',
    'Sora',
    '{"title":"Haunted Hallway","logline":"A lone figure walks a flickering hallway as shadows move.","style_lock":"low light, high contrast, cold blue shadows, subtle grain","characters":[{"id":"figure","anchors":"long coat, flashlight, tense posture","prompt":"Character reference sheet, figure in long coat, holding flashlight, tense posture, neutral pose, front view, side view, back view, cold blue light"}],"scene_prompt":"Old hallway, flickering lights, peeling paint, cold blue shadows, subtle fog.","shots":[{"id":1,"duration":4,"description":"Wide shot of the hallway as lights flicker.","transition":"cut","camera_movement":"slow dolly in","composition":"centered vanishing point","lighting":"flicker strobe","audio_sfx":"light buzz","prompt_en":"haunted hallway, flickering lights, cold blue shadows, cinematic horror"},{"id":2,"duration":4,"description":"Close-up of the flashlight beam shaking.","transition":"cut","camera_movement":"handheld close-up","composition":"tight beam","lighting":"sharp contrast","audio_sfx":"breath","prompt_en":"close-up flashlight beam shaking, high contrast, horror"},{"id":3,"duration":4,"description":"Medium shot as a shadow crosses behind the figure.","transition":"cut","camera_movement":"static medium","composition":"figure foreground","lighting":"cold rim light","audio_sfx":"whisper","prompt_en":"shadow passes behind figure, cold rim light, horror tension"},{"id":4,"duration":4,"description":"Match cut to a door creaking open at the end of the hall.","transition":"match cut","camera_movement":"slow push in","composition":"door framed","lighting":"faint spill","audio_sfx":"door creak","prompt_en":"door creaking open, end of hallway, faint light spill, horror"}],"master_prompt":"Haunted hallway horror, flickering lights, cold blue shadows, high contrast, cinematic tension.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Flicker and cold palette stay consistent."}',
    'https://fal.media/files/monkey/2wJ-7T3wK_3s4sF_q.png',
    '["horror","cinematic","thriller"]',
    230,
    65,
    false,
    true
  ),
  (
    'pp_019',
    'city-transit-montage',
    'City Transit Montage',
    'A fast montage of commuters and transit lines.',
    'Veo',
    '{"title":"City Transit Montage","logline":"A rapid montage of city transit from morning to night.","style_lock":"urban montage, sharp cuts, cool steel tones","characters":[],"scene_prompt":"City transit hubs, subway platforms, buses, crosswalks, cool steel tones.","shots":[{"id":1,"duration":3,"description":"Wide shot of commuters entering a subway station.","transition":"cut","camera_movement":"steady wide","composition":"wide crowd","lighting":"cool daylight","audio_sfx":"metro rumble","prompt_en":"commuters entering subway station, urban wide shot"},{"id":2,"duration":3,"description":"Close-up of train doors closing.","transition":"cut","camera_movement":"static close-up","composition":"tight doors","lighting":"cool fluorescent","audio_sfx":"door chime","prompt_en":"train doors closing, close-up, cool fluorescent"},{"id":3,"duration":3,"description":"Match cut to bus wheels rolling over wet street.","transition":"match cut","camera_movement":"low tracking","composition":"tight wheels","lighting":"street reflections","audio_sfx":"street hiss","prompt_en":"bus wheels rolling, wet street reflections, low tracking"},{"id":4,"duration":3,"description":"Wide aerial of traffic lines at dusk.","transition":"cut","camera_movement":"aerial glide","composition":"city grid","lighting":"blue hour","audio_sfx":"city hum","prompt_en":"aerial city traffic at dusk, blue hour, urban montage"}],"master_prompt":"City transit montage, sharp cuts, cool steel tones, urban energy, cinematic pacing.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Urban palette stays cool and metallic."}',
    'https://fal.media/files/panda/5pQ-2R9wS_1s7sE_z.png',
    '["montage","cinematic","documentary"]',
    210,
    55,
    false,
    true
  ),
  (
    'pp_020',
    'robot-factory-tour',
    'Robot Factory Tour',
    'A sleek industrial tour of a robot assembly line.',
    'Kling',
    '{"title":"Robot Factory Tour","logline":"An assembly line builds robots in a pristine factory.","style_lock":"industrial clean, cool white light, chrome reflections","characters":[{"id":"engineer","anchors":"gray uniform, safety glasses, tablet","prompt":"Character reference sheet, engineer in gray uniform, safety glasses, holding tablet, neutral pose, front view, side view, back view, cool white light"}],"scene_prompt":"Robot factory floor, assembly line arms, chrome surfaces, cool white light.","shots":[{"id":1,"duration":4,"description":"Wide shot of robotic arms moving along the assembly line.","transition":"cut","camera_movement":"slow dolly in","composition":"wide, repeating lines","lighting":"cool white","audio_sfx":"servo whirr","prompt_en":"robot assembly line, robotic arms, cool white light, industrial clean"},{"id":2,"duration":4,"description":"Close-up of a robotic hand placing a component.","transition":"cut","camera_movement":"macro push in","composition":"tight mechanical detail","lighting":"chrome reflections","audio_sfx":"metal click","prompt_en":"robotic hand placing component, macro detail, chrome reflections"},{"id":3,"duration":4,"description":"Medium shot of the engineer inspecting a finished unit.","transition":"cut","camera_movement":"steady medium","composition":"rule of thirds","lighting":"cool highlights","audio_sfx":"tablet beep","prompt_en":"engineer inspecting robot, gray uniform, tablet, cool factory light"},{"id":4,"duration":4,"description":"Wide shot of the line powering up in sync.","transition":"cut","camera_movement":"slow pull back","composition":"wide symmetry","lighting":"cool white glow","audio_sfx":"power hum","prompt_en":"assembly line powering up, synchronized robot arms, clean factory, cinematic"}],"master_prompt":"Robot factory tour, industrial clean, chrome reflections, cool white light, cinematic shot list.","negative_prompt":"low quality, blurry, watermark","continuity_notes":"Factory lighting stays cool white with chrome reflections."}',
    'https://fal.media/files/tiger/7jM-1X5wN_6s9sA_r.png',
    '["sci-fi","cinematic","documentary"]',
    200,
    50,
    false,
    true
  )
ON CONFLICT (uuid) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  model = EXCLUDED.model,
  content_json = EXCLUDED.content_json,
  thumbnail_url = EXCLUDED.thumbnail_url,
  tags = EXCLUDED.tags,
  views = EXCLUDED.views,
  copies = EXCLUDED.copies,
  is_featured = EXCLUDED.is_featured,
  is_public = EXCLUDED.is_public;
